import type { Language } from './types';

export const LOCAL_STORAGE_KEYS = {
  TEMPLATES: 'story-spark-templates',
  STORY: 'story-spark-story',
  STORYBOARD: 'story-spark-storyboard',
  LANGUAGE: 'story-spark-language',
};

export const LOCALIZATIONS: Record<Language, Record<string, string>> = {
  en: {
    'appTitle': 'Story Spark',
    'promptTemplates': 'Prompt Templates',
    'newTemplate': 'New Template',
    'templateName': 'Template Name (e.g., Sci-Fi Opening)',
    'templateContent': 'Template Content (use {{variable}} for placeholders)',
    'addTemplate': 'Add Template',
    'storyCanvas': 'Story Canvas',
    'selectTemplate': 'Select a template to start',
    'generateStory': 'Generate Story',
    'storyGeneration': 'Story Generation',
    'formattingStory': 'Formatting story...',
    'generatingStoryboard': 'Generating storyboard...',
    'generatingImage': 'Generating image...',
    'autoFormat': 'Auto-Format',
    'generateStoryboard': 'Generate Storyboard',
    'storyboard': 'Storyboard',
    'noStoryboard': 'Generate a storyboard from your story.',
    'scene': 'Scene',
    'camera': 'Camera',
    'setting': 'Setting',
    'action': 'Action',
    'dialogue': 'Dialogue',
    'visual': 'Visual',
    'generateImage': 'Generate Image',
    'errorOccurred': 'An error occurred. Please try again.',
    'delete': 'Delete',
    'storyPlaceholder': 'Your generated story will appear here...',
    'variables': 'Variables',
    'fillVariables': 'Fill in the variables from your template:',
    'noVariables': 'No variables (e.g., {{name}}) found in the template.',
    'storyTopic': 'Story Topic',
    'storyTopicPlaceholder': 'e.g., A young wizard discovers a hidden power.',
    'edit': 'Edit',
    'saveChanges': 'Save Changes',
    'cancel': 'Cancel',
    'optimizingTemplate': 'Optimizing template...',
    'autoOptimize': 'Auto-Optimize',
    'editTemplate': 'Edit Template',
  },
  zh: {
    'appTitle': '故事火花',
    'promptTemplates': '提示词模板',
    'newTemplate': '新模板',
    'templateName': '模板名称 (例如: 科幻开篇)',
    'templateContent': '模板内容 (使用 {{变量}} 作为占位符)',
    'addTemplate': '添加模板',
    'storyCanvas': '故事画布',
    'selectTemplate': '选择一个模板开始',
    'generateStory': '生成故事',
    'storyGeneration': '故事生成',
    'formattingStory': '正在格式化故事...',
    'generatingStoryboard': '正在生成分镜...',
    'generatingImage': '正在生成图片...',
    'autoFormat': '自动排版',
    'generateStoryboard': '生成分镜表',
    'storyboard': '分镜表',
    'noStoryboard': '从您的故事生成一个分镜表。',
    'scene': '场景',
    'camera': '镜头',
    'setting': '环境',
    'action': '动作',
    'dialogue': '对话',
    'visual': '视觉',
    'generateImage': '生成图片',
    'errorOccurred': '发生错误，请重试。',
    'delete': '删除',
    'storyPlaceholder': '您生成的故事将显示在这里...',
    'variables': '变量',
    'fillVariables': '请填写模板中的变量:',
    'noVariables': '模板中未找到变量 (例如 {{name}})。',
    'storyTopic': '故事主题',
    'storyTopicPlaceholder': '例如：一个年轻的巫师发现了隐藏的力量。',
    'edit': '编辑',
    'saveChanges': '保存更改',
    'cancel': '取消',
    'optimizingTemplate': '正在优化模板...',
    'autoOptimize': '自动优化',
    'editTemplate': '编辑模板',
  },
};